#!/usr/bin/env python3
"""
bake.py — freeze data/collection.json into data/collection.js so index.html
opens straight from the file system (double-click), no server needed.

    python3 bake.py

Opened this way the CMS is read-only — spectrum drags, notes, colour edits and
paste-a-URL all need the save API, so run `python3 serve.py` for those.
Re-run bake.py after any change you want to see in the double-click version.
"""
import json, os

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, "data", "collection.json")
OUT = os.path.join(ROOT, "data", "collection.js")

doc = json.load(open(SRC, encoding="utf-8"))
with open(OUT, "w", encoding="utf-8") as fh:
    fh.write("/* generated by bake.py — do not edit; run `python3 bake.py` */\n")
    fh.write("window.__COLLECTION = ")
    json.dump(doc, fh, ensure_ascii=False, separators=(",", ":"))
    fh.write(";\n")

print(f"wrote {OUT}  ({os.path.getsize(OUT)//1024} KB, {len(doc['items'])} items)")
